# Generated by Django 3.0.6 on 2020-05-14 19:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Yorking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_user',
            name='match_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='match_user',
            name='status',
            field=models.CharField(default='Not occured', max_length=200),
        ),
    ]
