# Generated by Django 3.0.6 on 2020-05-28 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Yorking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='Pravalika0106', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_team',
            name='user_id',
            field=models.ForeignKey(default='Pravalika0106', on_delete=django.db.models.deletion.CASCADE, to='Yorking.user'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='user_team',
            unique_together={('user_id', 'match_id')},
        ),
        migrations.RemoveField(
            model_name='user_team',
            name='user_name',
        ),
    ]
