# Generated by Django 3.0.6 on 2020-05-20 04:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Yorking', '0005_auto_20200520_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_team',
            name='player_id',
            field=models.UUIDField(default=uuid.UUID('99b88063-493a-4b70-8844-635a0170d416'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='match_user',
            name='match_id',
            field=models.UUIDField(default=uuid.UUID('30794fe4-8f50-4f07-9c30-baa794243517'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('f16ca910-9f40-4de5-b1f9-debd48cfda38'), editable=False, primary_key=True, serialize=False),
        ),
    ]
