# Generated by Django 3.0.6 on 2020-05-20 04:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Yorking', '0006_auto_20200520_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_team',
            name='player_id',
            field=models.UUIDField(default=uuid.UUID('84525b34-0256-4c0b-8529-2800e86efa7e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='match_user',
            name='match_id',
            field=models.UUIDField(default=uuid.UUID('2af04a7e-f0ce-4fca-9bfa-002e7a7687d8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('867f3e91-35a6-4108-90a3-81a1c916b355'), editable=False, primary_key=True, serialize=False),
        ),
    ]
