# Generated by Django 3.0.6 on 2020-05-21 14:55

import Yorking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yorking', '0008_auto_20200520_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_team',
            name='player_id',
            field=models.CharField(default=Yorking.models.uuid_hex, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='match_user',
            name='match_id',
            field=models.CharField(default=Yorking.models.uuid_hex, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=Yorking.models.uuid_hex, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
