# Generated by Django 3.0.6 on 2020-05-24 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Yorking', '0009_auto_20200521_2025'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='choosen_players',
            unique_together={('user_match', 'player_id')},
        ),
    ]
