# Generated by Django 3.0.6 on 2020-05-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yorking', '0010_auto_20200524_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phn_num',
        ),
        migrations.AddField(
            model_name='user_team',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
