# Generated by Django 3.0.6 on 2020-05-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pravalika', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match_performance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='match_performance',
            name='match_id',
        ),
        migrations.RemoveField(
            model_name='match_performance',
            name='player_id',
        ),
        migrations.AlterUniqueTogether(
            name='user_team',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='user_team',
            name='match_id',
        ),
        migrations.RemoveField(
            model_name='user_team',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='choosen_players',
        ),
        migrations.DeleteModel(
            name='country_team',
        ),
        migrations.DeleteModel(
            name='match_performance',
        ),
        migrations.DeleteModel(
            name='match_user',
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.DeleteModel(
            name='user_team',
        ),
    ]
