# Generated by Django 3.0.6 on 2020-05-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pravalika', '0003_choosen_players_country_team_match_performance_match_user_user_user_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_performance',
            name='match_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='match_performance',
            name='player_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='match_performance',
            unique_together=set(),
        ),
    ]
